<table>
    <tr>
        <td>oppenid</td>
        <td>用户昵称</td>
        <td>性别</td>
    </tr>
    <tr>
        <td>{{$userinfo['openid']}}</td>
        <td>{{$userinfo['nickname']}}</td>
        <td>{{$userinfo['sex']}}</td>
    </tr>
</table>